### ISSUE TITLE
Very Minor: chmod before zip?

### ISSUE THREAD

**Issue by iandol** [pandoc-extras/pandoc-nightly#3]
I normally have to chmod the pandoc executable after unzipping. Could +X be set by the build system before creating the zip files?

**Comment by ickc** [comment]
Sorry, somehow I missed this. I’ll take a look tomorrow. Which OS you use by the way?

Edit: I find out why I am not getting notifcations on this: http://alexking.org/blog/2011/11/28/not-getting-github-notifications

**Comment by ickc** [comment]
I tried both the linux build and the macOS build and they both are already executable. So I can't reproduce this problem. Can you give me more details?

**Comment by iandol** [comment]
Actually on further investigation this was a bug caused by my zip program, will close this now.

Thank you so much for the nightlies, it made it much easier to contribute to Pandoc development for those of us who are not developers!!!
