### ISSUE TITLE
Please make `pandoc-nightly` builds available as an AppImage

### ISSUE THREAD

**Issue by pdfkungfoo** [pandoc-extras/pandoc-nightly#4]
<sub>**Note:** This is basically a modified copy of [Pandoc issue #4029](https://github.com/jgm/pandoc/issues/4029). For a background to this request, see discussion over there.</sub>

----

I want to request an automatically built AppImage package for Pandoc-(Nightly). 

> ###  TL;DR
>
> An AppImage has the following advantages:
>
> 1. Directly runs on all major Linux distribution.
> 1. Similar functionality as "PortableApps" on Windows.
> 1. Directly runs from any location (even USB thumbdrives).
> 1. You can run different versions of the same software side-by-side.
> 1. No need to "install".
> 1. An AppImage is a single file.
>
> Technically, an AppImage is posing as a normal ELF binary. Inside, the most part of it is a compressed [AppDir](http://rox.sourceforge.net/desktop/AppDirs.html) (see [also Wikipedia](https://en.wikipedia.org/wiki/Application_directory)) containing the application alongside the required run-time libraries and resources. A small piece of extra code inside the AppImage auto-mounts the AppDir on a mount point in *`/tmp/`*.
>
> Then it executes the binary inside the AppImage.

So, AppImages aren't "packages" in the the sense of other software packages. 

The most basic principle of the AppImage format is: `"1 file == 1 appliation"`. Contrary to what the first reading of the [AppImage website](https://appimage.org/) may lead one to believe (*"this is for Desktop / GUI applications only"*), ***AppImages work very well for CLI tools too.*** **[^1]** <sub>*(I've successfully tested AppImages made from the `ippsample` software, provided by the ISTO Printer Working Group [PWG] for prototyping and testing IPP Everywhere [Internet Printing Protocol] software.)*</sub>.

The `"1 file == 1 application"` makes it very easy for users to make use of the software:

1. Download + save 1 file only.
1. Make it executable.
1. Run it (from whereever you stored it).

The `"1 file == 1 application"` makes it also very easy for developers to provide their software to their audience:

1. An AppImage runs on most Linux distribution without change.
1. Different versions of a software may be used side-by-side (important for testers / developers / reviewers / trainers).
1. Even officially un-released versions of the software can be easily made available to those who love to run (or have to test) the "bleeding edge".

It would be easy to integrate the automated build of an AppImage via Travis upon every single Git commit.

I'm pretty sure that @probonopd, the lead AppImage developer will help to setup an automatic workflow for Pandoc (maybe even prepare a pull request that you only need to test + accept). <sub>(After all, even Microsoft now builds [AppImages for their PowerShell 6.0.0 Betas](https://github.com/PowerShell/PowerShell/releases), capable to run on multiple Linux distributions.)</sub>

----

**[^1]:** One special case would apply to Pandoc: since it is only fully useful, if you also have the *`pandoc-citeproc`*-filter available, they should be bundled into the same AppImage. By creating two different symlinks some where in `$PATH` (f.e. `${HOME}/bin/`), *`pandoc`*  and *`pandoc-citeproc`* both pointing to the same executable AppImage, these both commands could be used independently from each other.

**Comment by probonopd** [comment]
Since pandoc-nightly is already a single file executable (kudos!), putting this into an AppImage is literally a matter of adding a desktop file, an icon, and running it through `appimagetool`.

**Comment by ickc** [comment]
Can you provide a bash script that can go from having 2 files (pandoc, pandoc-citeproc) to an appimage? I don't use that tool so I've no idea how to accomplish that.

**Comment by probonopd** [comment]
@KurtPfeifle if these are literally already single files, do you still see value in making AppImages?

**Comment by pdfkungfoo** [comment]
@probonopd:

Yes, because I want to be able to use a pandoc nightly AppImage right away after download, without unzipping and re-naming it first...

I'll be working on a script which accomplishes that and offer it as a PR to @ickc for integration here once it's tested. However, it will be a few more weeks before I come round to do it...

**Comment by ickc** [comment]
Download and unzip can be done using pipe (this has an advantage the download is not even written to disk. And then you can `&&` another command that move them (possibly with glob) to your desired location automatically.

But if you got the time to make it work with AppImage, sure we can add it here. Add a test in Travis to make sure it works, which can also serve as an example on how to use AppImage.

**Comment by pdfkungfoo** [comment]
@ickc:

Thanks for your advice.

> "Download and unzip can be done using pipe (this has an advantage the download is not even written to disk...."

I know, and sometimes I even do that. However, my handicap is that I need to very frequently use the *`-c`* with my wget: I'm on a rather slow and shaky internet connection.

**Comment by ickc** [comment]
Closing due to lack of interest.

**Comment by ghost** [comment]
I'm interested in this :v
